import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
  lang="en"
  className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
>
  <body className="min-h-screen flex flex-col relative overflow-x-hidden">
    
    {/* Fixed Gradient Background */}
    <div className="fixed inset-0 -z-10 bg-linear-to-br from-[#f4f3f2] via-[#eef6ee] to-[#e9f3ea]" />
    <Navbar />
    <main className="flex-1">
      {children}
    </main>
    <Footer />
  </body>
</html>
  );
}

// bg-[#ede8e0]